### ISSUE TITLE
Support for SSL and SCARM

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-lab#29]
Though it's old but nice one. Seems it's only supported plain (9092), would be great if it's support SSL and SCARM.

THANKS 👍 in advance.

**Comment by ppatierno** [comment]
If I understood your request correctly, it's everything already supported and the documentation explains it in detail, it's just a matter of spending more time searching for what you need there.

https://strimzi.io/docs/operators/master/using.html#assembly-securing-access-str

**Comment by scholzj** [comment]
@cloudcafetech I don't think we will be working to add it to the demos here. But you can always open a PR to add it.

**Comment by ppatierno** [comment]
@scholzj out of curiosity, where did you get he was referring to the demo/example files? are you able to read minds? ;-)

**Comment by scholzj** [comment]
The issue is opened in strimzi-lab repository. So I assume it refers to its content.

**Comment by cloudcafetech** [comment]
I am referring this IOT demo ONLY.

**Comment by scholzj** [comment]
Yeah, as I said, I don't think we plan to do any changes to them. Feel free to open a PR if you want.
