### ISSUE TITLE
Add CRUD application running on MySQL as source for CDC events

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-lab#3]
I have an [example CRUD application](https://github.com/gunnarmorling/hibernate-demos/tree/debezium-demo/hibernate-ogm/hiking-demo) based on MySQL and running on WildFly which I use in demos.

We could use this as a source for ingesting CDC events with Debezium during the lab. Currently, it's a "Hike Manager" application, but it's simple CRUD really only, so we might quite easily alter it into something more related to the IOT scenario. Maybe something for managing device master data?

We could:

* Create a Docker image with the CRUD app, e.g. based on the JBoss WildFly [base image](https://hub.docker.com/r/jboss/wildfly/)
* Create a MySQL image with the correct binlog config (we even might use the Debezium example image for MySQL for that)
* Let lab participants
  * set up instances of these images,
  * set up Kafka Connect with the Debezium MySql connector
  * deploy an instance of the connector, pointing to the database set up before
  * consume messages with the console consumer, seeing changes there as they alter data in the CRUD app

That's the most simple demo I'm usually doing of Debezium. Then, depending on how far we want to go, we could let the participants:

* Set up another DB instance, e.g. Postgres
* Set up an instance of the JDBC sink connector, pointing to the CDC topic set up before, and sinking events into Postgres
* explore how the app keeps running also if KC is down and how changes will show up in Postgres once it's up again

and the last step I'm doing in my Debezium demos is to show how to consume CDC messages using WildFly Swarm and CDI and push them to another browser window using WebSockets. This might be too much for this lab, tough, and lead away too much from the things we want to show.

@mbogoevici, @ppatierno, any thoughts on that? I think i'll prepare a PR with the CRUD app to be added to this repo in any case, as it seems a good first step.

**Comment by gunnarmorling** [comment]
One question I have: can we have participants pull images from hub.docker.com during the lab, or should we preceed the VM's local registry with all images needed?

**Comment by ppatierno** [comment]
@gunnarmorling can I close this issue ?

**Comment by gunnarmorling** [comment]
Yes, let's close it :)
